### ISSUE TITLE
Crear la tabla CamaraAplicaciones

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#18]
Se debe crear la tabla CamaraAplicaciones la cual tendrá en su contenido toda la información relacionada acerca de las aplicaciones de la tienda.

**Comment by ronaldfabra** [comment]
Se creó la tabla CamaraAplicaciones la cual tendrá toda la información relacionada acerca de cada aplicación que se quiera conocer.
esto se puede ver acontinuación:
![image](https://user-images.githubusercontent.com/30238979/29273634-a1b1e060-80ca-11e7-8f19-8285214b7bfb.png)

**Comment by jpllinasCCSM** [comment]
Los nombres de las y¿tabals deben ser como en el esquema, porque estan todo en mayusculas?

**Comment by ronaldfabra** [comment]
Se actualizó el nombre de la tabla por CamaraAplicaciones cómo en el esquema anteriormente diseñado, esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29368564-b52db7da-8265-11e7-9ce6-13023651faed.png)
