### ISSUE TITLE
Crear la tabla CamaraCategorias

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#20]
Se debe crear la tabla CamaraCategorias la cual tendrá la información relacionada con las categorías que existen.

**Comment by ronaldfabra** [comment]
Se creó la tabla CamaraCategorias la cual tendrá toda la información relacionada acerca de cada categoria que se quiera conocer.
esto se puede ver acontinuación:
![image](https://user-images.githubusercontent.com/30238979/29274323-12bf81f2-80cd-11e7-9809-bc50052601dd.png)

**Comment by jpllinasCCSM** [comment]
El nombre de la tabla debe ser como en el esquema diseñado.

**Comment by ronaldfabra** [comment]
Se actualizó el nombre de la tabla por CamaraCategorias cómo en el esquema anteriormente diseñado, esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29368673-091220a2-8266-11e7-8d4a-81fbe376a28a.png)
