### ISSUE TITLE
Crear la tabla CamaraAplicacionesTipos

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#22]
Se debe crear la tabla CamaraAplicacionesTipos la cual tendrá la información relacionada con los tipos de las aplicaciones.

**Comment by ronaldfabra** [comment]
Se creó la tabla CamaraAplicacionesTipos la cual tendrá toda la información relacionada acerca de los tipos de aplicaciones que se tienen en la tienda de apps.
esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29274759-82e5fa0a-80ce-11e7-8551-a7e64314230e.png)

**Comment by jpllinasCCSM** [comment]
El nombre de la tabla debe ser como en el esquema diseñado.

**Comment by ronaldfabra** [comment]
Se actualizó el nombre de la tabla por CamaraAplicacionesTipos cómo en el esquema anteriormente diseñado, esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29368736-36490cd4-8266-11e7-8672-2b5b484275d7.png)
