### ISSUE TITLE
Seleccionar la plantilla para la tienda

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#27]
Se debe seleccionar la mejor plantilla del listado que se tiene anteriormente la cual debe cumplir con todos los requerimientos de la tienda de Apps.

1. Pagina Home
2. Pagina de la App

**Comment by jpllinasCCSM** [comment]
Se elige trabajar con la plantilla http://p.w3layouts.com/demos/bak_one/web/
