### ISSUE TITLE
Diseñar el modelo de la Base de Datos

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#31]
Se debe diseñar primeramente la base de datos donde estará almacenada toda la información relacionada con las aplicaciones en general, el cual deberá ser un borrador de cómo estarán estructurados los datos de la página.

**Comment by ronaldfabra** [comment]
Se diseñó el modelo de Base de datos en el software de MYSQL Workbench el cual será utilizado para la administración de los datos que se requieren mostrar en la página, este modelo cuenta con las tablas principales que se utilizarán el cual se puede observar en el siguiente enlace.
https://user-images.githubusercontent.com/30238979/29074754-02c230bc-7c16-11e7-9f9c-587cf6193207.png

**Comment by jpllinasCCSM** [comment]
El diseño no cumple con las condiciones para ser comprensible. En este se deben consigar, todos los atributos y relaciones que existirían en los datos

**Comment by ronaldfabra** [comment]
Se verificó y actualizó el diseñó del modelo de Base de datos en el software de MYSQL Workbench, este modelo cuenta con las tablas principales, atributos y sus relaciones, que se utilizarán el cual se puede observar en el siguiente enlace.
https://user-images.githubusercontent.com/30238979/29191067-08a2bb3c-7de2-11e7-9410-918f5c3aea55.png

**Comment by ronaldfabra** [comment]
[dbaplicaciones.zip](https://github.com/CamComercioSM/apps/files/1216359/dbaplicaciones.zip)

**Comment by ronaldfabra** [comment]
Se verificó y actualizó el diseñó del modelo de Base de datos en el software de MYSQL Workbench, este modelo cuenta con las tablas principales, atributos y sus relaciones, que se utilizarán el cual se puede observar en el siguiente enlace.

[Aplicaciones.zip](https://github.com/CamComercioSM/apps/files/1217999/Aplicaciones.zip)

**Comment by jpllinasCCSM** [comment]
Donde está el modelo definitivo??

**Comment by ronaldfabra** [comment]
El modelo definitivo se puede ver a continuacion:
![image](https://user-images.githubusercontent.com/30238979/29220879-21499c1e-7e82-11e7-8ad7-e2e65f85e33b.png)
 
O si desea descargarlo:
[Aplicaciones.zip](https://github.com/CamComercioSM/apps/files/1218371/Aplicaciones.zip)
