### ISSUE TITLE
Identificar los atributos de la tabla CamaraAplicaciones

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#33]
Se debe identificar todos los atributos que sean importantes y puedan usarse en la tabla CamaraAplicaciones, y posteriormente verificar si están en el modelo y hacer un listado con sus características.

**Comment by ronaldfabra** [comment]
Se identificaron los atributos propios de la tabla Aplicacion, los cuales serán los datos más importantes que tendrán cada una de las aplicaciones para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son: 

1. IdAplicacion
2. Nombre
3. Descripción

Estos atributos podrán verse en el siguiente link:

https://user-images.githubusercontent.com/30238979/29075194-4d8dc038-7c17-11e7-8ac0-0098b3aeddb2.png

**Comment by ronaldfabra** [comment]
Se identificaron y actualizaron los atributos propios de la tabla CamaraAplicaciones, para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son:

aplicacionID (Tipo INT,Llave primaria, Auto-incrementable)
aplicacionCODIGO (Tipo VARCHAR[25])
aplicacionTITULO (Tipo VARCHAR[25])
aplicacionDESCRIPCION (Tipo TEXT)
aplicacionICONO (Tipo TEXT)
aplicacionURL (Tipo TEXT)
aplicacionULTCOMMIT (Tipo TEXT)
aplicacionVERSION (Tipo VARCHAR[10], NO NULL)
aplicacionFECHACTULIZACION (Tipo DATE)
aplicacionFECHALANZAMIENTO (Tipo DATE)
aplicacionFECHASUSPENSION (Tipo DATE)
aplicacionESTADO Tipo (ENUM('EN DESARROLLO', 'PRUEBAS', 'PRODUCCIÓN', 'SUSPENDIDA', 'PLANEACIÓN', NO NULL)
aplicacionPOLITICA (TIPO INT[11], NO NULL)
aplicacionTipoID (TIPO INT, NO NULL)

Estos atributos podrán verse en el siguiente link:
![image](https://user-images.githubusercontent.com/30238979/29195224-f046830a-7df2-11e7-8664-58babd94887a.png)

**Comment by jpllinasCCSM** [comment]
Ojo con los tamaños de los campos en las tablas. El campo aplicacionTipoID no dice que longitud será.
