### ISSUE TITLE
Identificar los atributos de la tabla CamaraCategorias

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#34]
Se debe identificar todos los atributos que sean importantes y puedan usarse en la tabla CamaraCategorias, y posteriormente verificar si están en el modelo y hacer un listado con sus características.

**Comment by ronaldfabra** [comment]
Se identificaron los atributos propios de la tabla CategoriaAplicacion, los cuales serán los datos más importantes que tendrán cada una de las categorias para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son:

IdCategoriaAplicacion
Nombre

Estos atributos podrán verse en el siguiente link:
https://user-images.githubusercontent.com/30238979/29075353-ae8da718-7c17-11e7-9cc6-7aa425d06f6a.png

**Comment by ronaldfabra** [comment]
Se identificaron y actualizaron los atributos propios de la tabla CamaraCategorias, para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son:

categoriaID (TIPO INT, LLAVE PRIMARIA,NO NULL)
categoriaTipoID (TIPO INT)
categoriaCODIGO (TIPO VARCHAR[25])
categoriaTITULO (TIPO VARCHAR[25])
categoriaDESCRIPCION (TIPO TEXT)
categoriaFECHCREA (TIPO TIMESTAMP, NO NULL)

Estos atributos podrán verse en la siguiente imagen:

**Comment by jpllinasCCSM** [comment]
por favor cambiar el nobre del campo categorioFECHCREA por categoriaFCHCREADO

**Comment by ronaldfabra** [comment]
Se realizó la respectiva actualización del campo categorioFECHCREA por categoriaFCHCREADO, como se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29220130-c203f684-7e7f-11e7-8231-264a5f1e535e.png)
