### ISSUE TITLE
Identificar los atributos de la tabla CamaraAplicacionesTipos

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#35]
Se debe identificar todos los atributos que sean importantes y puedan usarse en la tabla CamaraAplicacionesTipos, y posteriormente verificar si están en el modelo y hacer un listado con sus características.

**Comment by ronaldfabra** [comment]
Se identificaron los atributos propios de la tabla TipoAplicacion, los cuales serán los datos más importantes que tendrán cada uno de los tipos para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son:

IdTipoAplicacion (Tipo INT,Llave primaria, Auto-incrementable, No-Null)
Nombre(Tipo VARCHAR[45], No-Null)

Estos atributos podrán verse en el siguiente link:
https://user-images.githubusercontent.com/30238979/29075619-91d7001e-7c18-11e7-8091-e97de92ee500.png

**Comment by ronaldfabra** [comment]
Se identificaron y actualizaron los atributos propios de la tabla CamaraAplicacionesTipos, para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son:

aplicacionTipoID (TIPO INT, LLAVE PRIMARIA,NO NULL, CODIGO UNICO, AUTO-INCREMENTAL)
aplicacionTipoCODIGO (TIPO VARCHAR[25])
aplicacionTipoTITULO (TIPO VARCHAR[25])
aplicacionTipoDESCRIPCION (TIPO TEXT)
AplicacionTipoFECHCREA  (TIPO TIMESTAMP, NO NULL)

Estos atributos podrán verse en la siguiente imagen:

![image](https://user-images.githubusercontent.com/30238979/29195350-a6f9da8e-7df3-11e7-999a-46c30b4d3c92.png)

**Comment by jpllinasCCSM** [comment]
Por favor cambir el nombre del campo AplicacionTipoFECHCREA por aplicacionTipoFCHCREADO

**Comment by ronaldfabra** [comment]
se realizó el cambio del nombre del campo AplicacionTipoFECHCREA por aplicacionTipoFCHCREADO como puede verse a continuación:
![image](https://user-images.githubusercontent.com/30238979/29220229-0a50e708-7e80-11e7-8e0d-9fd5e22a3a90.png)
