### ISSUE TITLE
Cambiar los datos e información en la plantilla seleccionada

### ISSUE THREAD

**Issue by jpllinasCCSM** [CamComercioSM/apps#45]
El titulo de la pagina deberá ser: "Centro de Aplicaciones @CamComercioSM"

Los menú deberán ser : 
- Inicio 
- Aplicaciones
- Contacto

Se debe eliminar la zona debajo de la cabecera, identificada en el DOM con la clase **slider_bg**.

Se debe eliminar el texto :
Portfolio
Lorem Ipsum is simply dummy text of the printing and typesetting industry.

El formulario de contacto debe estar todo en español.

En la zona de información debe estar los datos de contacto del centro de Servicios TICS

**Comment by ronaldfabra** [comment]
Se actualizo título de la página por Centro de Aplicaciones @CamComercioSM
