### ISSUE TITLE
Identificar los atributos de la tabla CamaraCategoriasTipos

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#50]
Se debe identificar todos los atributos que sean importantes y puedan usarse en la tabla CamaraCategoriasTipos, y posteriormente verificar si están en el modelo y hacer un listado con sus características.

**Comment by ronaldfabra** [comment]
Se identificaron los atributos propios de la tabla CamaraCategoriasTipos, para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son:

categoriaTipoID (TIPO INT, LLAVE PRIMARIA,NO NULL)
categoriaTipoCODIGO (TIPO VARCHAR[25])
categoriaTipoTITULO (TIPO VARCHAR[25])
categoriaTipoDESCRIPCION (TIPO TEXT)
categoriaTipoFECHCREA (TIPO TIMESTAMP, NO NULL)

Estos atributos podrán verse en la siguiente imagen:

![image](https://user-images.githubusercontent.com/30238979/29214182-e3221846-7e6b-11e7-8410-a9300c7e23c0.png)

**Comment by jpllinasCCSM** [comment]
Por favor cambiar el nombre del campo categoriaTipoFECHCREA por categoriaTipoFCHCREADO

**Comment by ronaldfabra** [comment]
Se realizó el cambio en el nombre del campo categoriaTipoFECHCREA por categoriaTipoFCHCREADO como puede verse a continuación:
![image](https://user-images.githubusercontent.com/30238979/29220297-35eaf8cc-7e80-11e7-92d7-cc750f534f79.png)
