### ISSUE TITLE
Identificar los atributos de la tabla CamaraAplicacionesCategorias

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#52]
Se debe identificar todos los atributos que sean importantes y puedan usarse en la tabla CamaraAplicacionesCategorias, y posteriormente verificar si están en el modelo y hacer un listado con sus características.

**Comment by ronaldfabra** [comment]
Se identificaron los atributos propios de la tabla CamaraAplicacionesCategorias, para que puedan ser manipulados o gestionados.
Los atributos de dicha tabla son:

categoriaID (TIPO INT,NO NULL)
aplicacionID (TIPO INT[11], NO NULL)

Estos atributos podrán verse en la siguiente imagen:

![image](https://user-images.githubusercontent.com/30238979/29214524-4cffc50a-7e6d-11e7-9335-10e03e464fc2.png)

**Comment by jpllinasCCSM** [comment]
Ah esta tabla le falta la primary key o la colunma que va servir para identifiacar la relación.

**Comment by ronaldfabra** [comment]
Se realizó  la actualización de la tabla agregandole la columna identificadora de la relación como se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29220597-2e68cf9c-7e81-11e7-8aa1-c3a2d7bbe7d1.png)
