### ISSUE TITLE
Crear la tabla CamaraCategoriasTipos

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#53]
Se debe crear la tabla CamaraCategoriasTipos la cual tendrá la información relacionada con los tipos de categorías que existen.

**Comment by ronaldfabra** [comment]
Se creó la tabla CamaraCategoriasTipos la cual tendrá toda la información relacionada acerca de los tipos de categorías que se tienen.
esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29274878-e903f5ee-80ce-11e7-89ea-1b8c290b38a5.png)

**Comment by jpllinasCCSM** [comment]
El nombre de la tabla debe ser como en el esquema diseñado.

**Comment by ronaldfabra** [comment]
Se actualizó el nombre de la tabla por CamaraCategoriasTipos cómo en el esquema anteriormente diseñado, esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29368808-6443d60a-8266-11e7-87ba-62c7e42a08ce.png)
