### ISSUE TITLE
Crear la tabla CamaraPoliticas

### ISSUE THREAD

**Issue by ronaldfabra** [CamComercioSM/apps#54]
Se debe crear la tabla CamaraPoliticas la cual tendrá la información relacionada con las politicas de las aplicaciones.

**Comment by ronaldfabra** [comment]
Se creó la tabla CamaraPoliticas la cual tendrá toda la información relacionada acerca de las políticas que se usan.
esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29274073-244d0a1c-80cc-11e7-83ad-b49fe0147395.png)

**Comment by jpllinasCCSM** [comment]
Nuevamente. El nombre de la tabla debe ser tal y como quedo en el esquema diseñado.

**Comment by ronaldfabra** [comment]
Se actualizó el nombre de la tabla por CamaraPoliticas cómo en el esquema anteriormente diseñado, esto se puede ver a continuación:
![image](https://user-images.githubusercontent.com/30238979/29368627-df111470-8265-11e7-945b-e09c2c4dc69f.png)
